# Generated by Django 4.0.4 on 2024-01-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='products',
        ),
    ]
